ports:
  - port: 8080 #NodeRed
    onOpen: ignore #open-preview
  - port: 8050  #VitalsFaker
  - port: 8090 #JSONserver
tasks:
  - before: npm install -g --unsafe-perm node-red && npm install --prefix ./VitalsFaker json-server faker fs
 # - command: gp await-port 8080
    init: npm start
    command: npm start